/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,html,css}"],
	theme: {
		extend: {
			fontFamily: {
				sans: ['"Funnel Display"', 'system-ui', '-apple-system', 'sans-serif'],
				funnel: ['"Funnel Display"', 'serif'],
			},

			colors: {
				primary: "#0077FD",
				secondary: "#f59e0b",
				accent: "#f97316",
				background: "#f3f4f6",
				text: "#111827",

				/**
				 * The register system.
				 *
				 * Ratevo makes four different kinds of statement and they must never
				 * be mistakable for one another:
				 *
				 *   measured    deep blue   computed by ratevo-analytics, always numeric
				 *   ai          light blue  interpretation, generated by a language model
				 *   evidence    teal        attributed to an external, citable source
				 *   possible    amber       plausible but unconfirmed
				 *
				 * `measured` and `ai` are both blue by design, so they are told apart
				 * by VALUE rather than by hue — measured is the dark, authoritative
				 * blue and ai is the lighter, airier one. Do not reintroduce a
				 * second hue here to "fix" the similarity: a product carrying a
				 * derived number and a generated interpretation wants one quiet
				 * family, and the difference between them is carried by weight,
				 * fill and the register pill as well as by shade.
				 *
				 * Phase 1 ships measured only. The other three exist in the tokens
				 * from the start so the language is consistent when those phases
				 * land, rather than being invented alongside them.
				 *
				 * These must sit *inside* `colors` or Tailwind silently ignores
				 * them. As siblings of it they produced no utilities at all, and
				 * every `bg-measured-soft` in the analytics panel was quietly
				 * rendering as no colour — which looks like a design decision
				 * rather than a broken one, so it survived a long time.
				 */
				measured: {
					DEFAULT: "#2b4ed8",
					deep: "#1c39a8",
					soft: "#e9eefc",
					line: "#c8d5f8",
				},
				ai: {
					DEFAULT: "#4a9eff",
					deep: "#2b7fd4",
					soft: "#e4f1ff",
					line: "#b3d7fb",
				},
				evidence: {
					DEFAULT: "#0b7a68",
					soft: "#e2f4f0",
					line: "#bfe4dc",
				},
				possible: {
					DEFAULT: "#8f5605",
					soft: "#fdf1dd",
					line: "#f2ddb4",
				},
				direction: {
					up: "#0f7a53",
					upSoft: "#e2f3ec",
					down: "#b3263f",
					downSoft: "#fdeaee",
				},
			},

			borderRadius: {
				xl: "0.875rem", // 14px — the card radius used across the product
				"2xl": "1rem", // 16px
				"3xl": "1.25rem", // 20px
			},

			boxShadow: {
				card: "0 1px 2px rgba(18,24,40,.05), 0 1px 1px rgba(18,24,40,.03)",
				raised: "0 2px 4px rgba(18,24,40,.04), 0 8px 20px -8px rgba(18,24,40,.12)",
			},
		},
	},
	plugins: [],
};
